"""Export the scenario definitions to language-neutral JSON.

`bench-rust/` drives the Rust binary through the *same* scenarios as
`bench-python/`. If each project kept its own copy, a scenario added to one would
quietly not exist in the other, and the two suites would drift into measuring
different things while still looking comparable, which is worse than not
comparing at all.

So the Python definitions are the single source and this exports them. The
graders are *not* exported: they are Python that imports the agent's output code
and executes it, so `bench-rust` shells out to them rather than reimplementing
them. What crosses the boundary is the part that must match exactly, the ids,
the prompts, and the turn text.

    python export_scenarios.py            # writes ../scenarios.json
    python export_scenarios.py --check    # verifies the file is current, writes nothing

`--check` is the useful one in CI and before a benchmark run: it fails if someone
edited a scenario and did not re-export, which would mean the two suites are
already measuring different things.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from bench import scenarios as bench_scenarios      # noqa: E402
from versus import scenarios as versus_scenarios    # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "scenarios.json")


def _grader_name(fn):
    """The grader's function name, which is the handle `bench-rust` passes back
    to Python. Not the grader itself: it is executable code, not data."""
    return getattr(fn, "__name__", "") if fn else ""


def export():
    bench = [
        {
            "id": s["id"],
            "name": s["name"],
            "kind": s["kind"],
            "difficulty": s.get("difficulty", ""),
            "request": s["request"],
            "grader": _grader_name(s.get("grade")),
            "answer_grader": _grader_name(s.get("grade_answer")),
            "turn_grader": _grader_name(s.get("grade_turn")),
            # The mechanism scenarios need more than one turn, and bench-rust
            # drives each turn as its own process, so it needs these too.
            "warmup": s.get("warmup", ""),
            "followup": s.get("followup", ""),
            "pristine_copy": bool(s.get("pristine_copy")),
            # Which ablation flag should reopen this scenario's failure. Gate 5
            # is exactly "run with this flag and check that it does".
            "ablation": s.get("ablation", ""),
        }
        # ALL, not SCENARIOS: the three behaviour scenarios (X1-X3) live in a
        # separate list, and the first export silently left them out.
        for s in bench_scenarios.ALL
    ]
    versus = [
        {
            "id": s["id"],
            "name": s["name"],
            "axis": s["axis"],
            # Turn text is deliberately agent-neutral, no tool names, no
            # framework vocabulary, so the same words can be handed to either
            # implementation without favouring one.
            "turns": [t["text"] for t in s["turns"]],
            "grader": _grader_name(s.get("grade")),
        }
        for s in versus_scenarios.ALL
    ]
    return {
        "schema": 2,
        "filler": bench_scenarios.MECHANISM_FILLER,
        "note": ("Generated by bench-python/export_scenarios.py. Edit the Python "
                 "definitions, not this file, then re-export."),
        "bench": bench,
        "versus": versus,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify scenarios.json is current; write nothing")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    data = export()
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        if not os.path.exists(args.out):
            print(f"MISSING {args.out}: run: python export_scenarios.py")
            return 1
        with open(args.out, encoding="utf-8") as f:
            current = f.read()
        if current != text:
            print(f"STALE {args.out}: a scenario changed but was not re-exported.\n"
                  f"      bench-python and bench-rust are measuring different things.\n"
                  f"      fix: python export_scenarios.py")
            return 1
        print(f"current: {len(data['bench'])} bench + {len(data['versus'])} versus scenarios")
        return 0

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {args.out}: {len(data['bench'])} bench + "
          f"{len(data['versus'])} versus scenarios")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
